const express = require('express');
const app = express();
const PORT = 5000;

app.get('/api', (req, res) =>{
    res.json({users: [{"id":"39-6423953","buzzword":"static","catch_phrase":"Re-contextualized even-keeled knowledge user","company_name":"Riffpath","departament":"Research and Development","duns":"92-197-6169","avatar":"https://robohash.org/optiovelitaut.png?size=50x50&set=set1","fake_company_name":"Mosciski, Crooks and Mueller"},
    {"id":"90-1005493","buzzword":"portal","catch_phrase":"Object-based demand-driven artificial intelligence","company_name":"Photospace","departament":"Product Management","duns":"47-898-3499","avatar":"https://robohash.org/itaquenihilest.png?size=50x50&set=set1","fake_company_name":"Beatty and Sons"},
    {"id":"36-9879102","buzzword":"optimizing","catch_phrase":"Monitored full-range focus group","company_name":"Camido","departament":"Training","duns":"62-413-0288","avatar":"https://robohash.org/modivoluptateslibero.png?size=50x50&set=set1","fake_company_name":"Barton-Gibson"},
    {"id":"29-0954518","buzzword":"intermediate","catch_phrase":"Programmable bandwidth-monitored contingency","company_name":"Dynabox","departament":"Legal","duns":"39-458-0291","avatar":"https://robohash.org/molestiaequisquamsed.png?size=50x50&set=set1","fake_company_name":"Smith, Schaden and Erdman"},
    {"id":"37-5025811","buzzword":"Progressive","catch_phrase":"Cross-group system-worthy circuit","company_name":"Realpoint","departament":"Human Resources","duns":"10-436-9519","avatar":"https://robohash.org/mollitiadistinctioet.png?size=50x50&set=set1","fake_company_name":"Cronin-Lubowitz"},
    {"id":"08-7566021","buzzword":"toolset","catch_phrase":"Sharable bottom-line implementation","company_name":"Yakidoo","departament":"Training","duns":"54-376-7530","avatar":"https://robohash.org/pariaturvelitaut.png?size=50x50&set=set1","fake_company_name":"Gutkowski, Waelchi and O'Keefe"},
    {"id":"82-3951342","buzzword":"array","catch_phrase":"Phased interactive monitoring","company_name":"Rhynyx","departament":"Human Resources","duns":"93-742-9564","avatar":"https://robohash.org/eosetporro.png?size=50x50&set=set1","fake_company_name":"Wintheiser LLC"},
    {"id":"80-8857211","buzzword":"user-facing","catch_phrase":"De-engineered eco-centric portal","company_name":"Browseblab","departament":"Research and Development","duns":"99-018-2552","avatar":"https://robohash.org/utvoluptatumquisquam.png?size=50x50&set=set1","fake_company_name":"Bartoletti, O'Conner and Dach"},
    {"id":"11-8316207","buzzword":"system-worthy","catch_phrase":"Polarised contextually-based methodology","company_name":"Meemm","departament":"Legal","duns":"24-822-1961","avatar":"https://robohash.org/nonistereprehenderit.png?size=50x50&set=set1","fake_company_name":"White, Zemlak and Lueilwitz"},
    {"id":"65-1962877","buzzword":"application","catch_phrase":"Synchronised zero tolerance approach","company_name":"Livefish","departament":"Marketing","duns":"61-399-9080","avatar":"https://robohash.org/animicommodiet.png?size=50x50&set=set1","fake_company_name":"Raynor-Lakin"},
    {"id":"44-8269595","buzzword":"tangible","catch_phrase":"Phased 3rd generation support","company_name":"Oyonder","departament":"Accounting","duns":"24-221-0900","avatar":"https://robohash.org/molestiasquiea.png?size=50x50&set=set1","fake_company_name":"Pacocha-Hagenes"},
    {"id":"45-7220330","buzzword":"archive","catch_phrase":"Decentralized dynamic instruction set","company_name":"Thoughtstorm","departament":"Research and Development","duns":"84-342-2213","avatar":"https://robohash.org/harumvelerror.png?size=50x50&set=set1","fake_company_name":"Fritsch LLC"},
    {"id":"72-3482655","buzzword":"Synergized","catch_phrase":"Multi-lateral fault-tolerant matrices","company_name":"Topdrive","departament":"Services","duns":"58-925-9577","avatar":"https://robohash.org/quibusdaminventoretemporibus.png?size=50x50&set=set1","fake_company_name":"Jacobi Group"},
    {"id":"86-3288127","buzzword":"mobile","catch_phrase":"Polarised encompassing forecast","company_name":"Skyvu","departament":"Accounting","duns":"43-787-7374","avatar":"https://robohash.org/temporateneturcum.png?size=50x50&set=set1","fake_company_name":"King and Sons"},
    {"id":"00-0040470","buzzword":"solution-oriented","catch_phrase":"Reverse-engineered responsive flexibility","company_name":"Muxo","departament":"Research and Development","duns":"32-235-7641","avatar":"https://robohash.org/ametetquaerat.png?size=50x50&set=set1","fake_company_name":"Bednar, Lynch and Tremblay"},
    {"id":"72-5384527","buzzword":"Synchronised","catch_phrase":"Seamless analyzing project","company_name":"Rhynyx","departament":"Sales","duns":"33-748-8304","avatar":"https://robohash.org/voluptatibuspraesentiumut.png?size=50x50&set=set1","fake_company_name":"Murray-Koepp"},
    {"id":"91-9387654","buzzword":"incremental","catch_phrase":"Operative local data-warehouse","company_name":"Trunyx","departament":"Legal","duns":"51-253-6037","avatar":"https://robohash.org/etearumquis.png?size=50x50&set=set1","fake_company_name":"Jerde, Heidenreich and Wehner"},
    {"id":"08-0832792","buzzword":"Devolved","catch_phrase":"Quality-focused next generation hierarchy","company_name":"Jaxbean","departament":"Business Development","duns":"87-102-9633","avatar":"https://robohash.org/voluptatemverofugit.png?size=50x50&set=set1","fake_company_name":"Mitchell-Lueilwitz"},
    {"id":"94-1422527","buzzword":"6th generation","catch_phrase":"Operative bifurcated superstructure","company_name":"Zoozzy","departament":"Support","duns":"06-117-3902","avatar":"https://robohash.org/rerumautcorporis.png?size=50x50&set=set1","fake_company_name":"Roberts-Pacocha"},
    {"id":"99-3147901","buzzword":"zero tolerance","catch_phrase":"Configurable transitional conglomeration","company_name":"Plambee","departament":"Marketing","duns":"93-698-5274","avatar":"https://robohash.org/temporadoloremquis.png?size=50x50&set=set1","fake_company_name":"Koss, D'Amore and Buckridge"},
    {"id":"41-5235683","buzzword":"dynamic","catch_phrase":"Synergistic empowering benchmark","company_name":"Meejo","departament":"Accounting","duns":"74-651-9644","avatar":"https://robohash.org/idnumquamplaceat.png?size=50x50&set=set1","fake_company_name":"O'Kon-Bahringer"},
    {"id":"72-7476244","buzzword":"matrix","catch_phrase":"Realigned interactive knowledge base","company_name":"Eidel","departament":"Legal","duns":"98-674-9670","avatar":"https://robohash.org/doloribussitut.png?size=50x50&set=set1","fake_company_name":"Hirthe and Sons"},
    {"id":"36-4827002","buzzword":"initiative","catch_phrase":"Multi-lateral reciprocal help-desk","company_name":"Eadel","departament":"Business Development","duns":"63-182-0909","avatar":"https://robohash.org/quisremnobis.png?size=50x50&set=set1","fake_company_name":"Doyle Inc"},
    {"id":"39-2731854","buzzword":"Grass-roots","catch_phrase":"Polarised value-added architecture","company_name":"Buzzbean","departament":"Training","duns":"47-832-1244","avatar":"https://robohash.org/providentomniseaque.png?size=50x50&set=set1","fake_company_name":"Lueilwitz, Monahan and Kozey"},
    {"id":"19-3973324","buzzword":"application","catch_phrase":"Triple-buffered bandwidth-monitored attitude","company_name":"Ozu","departament":"Sales","duns":"38-591-2245","avatar":"https://robohash.org/nisicumquisquam.png?size=50x50&set=set1","fake_company_name":"Blanda-Baumbach"},
    {"id":"58-8360778","buzzword":"Customizable","catch_phrase":"Automated discrete challenge","company_name":"Voonder","departament":"Business Development","duns":"08-753-4132","avatar":"https://robohash.org/architectoofficiiscommodi.png?size=50x50&set=set1","fake_company_name":"Dicki, Funk and Koch"},
    {"id":"95-8483040","buzzword":"Front-line","catch_phrase":"Assimilated zero administration algorithm","company_name":"Centimia","departament":"Engineering","duns":"63-876-0143","avatar":"https://robohash.org/mollitiaidet.png?size=50x50&set=set1","fake_company_name":"Bechtelar Group"},
    {"id":"18-2578060","buzzword":"real-time","catch_phrase":"Total zero defect parallelism","company_name":"Skidoo","departament":"Training","duns":"05-874-3126","avatar":"https://robohash.org/istequibusdamvoluptas.png?size=50x50&set=set1","fake_company_name":"Grimes Inc"},
    {"id":"99-0338778","buzzword":"Enterprise-wide","catch_phrase":"Persevering radical success","company_name":"Plajo","departament":"Marketing","duns":"77-820-4211","avatar":"https://robohash.org/autessesed.png?size=50x50&set=set1","fake_company_name":"Barton LLC"},
    {"id":"72-6923570","buzzword":"orchestration","catch_phrase":"Secured static focus group","company_name":"Edgeify","departament":"Research and Development","duns":"80-648-5766","avatar":"https://robohash.org/minimadebitissed.png?size=50x50&set=set1","fake_company_name":"O'Reilly, Kessler and Torphy"}]})
})
app.listen(PORT, () => console.log(`Server on port ${PORT}`));